name: Deploy Orders Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout `orders-service`
        uses: actions/checkout@v3

      - name: Clone `aws-infraestructure`
        run: |
          git clone https://github.com/angelmartinezt1/aws-infraestructure-test.git aws-infraestructure

      - name: Copy `orders-service` Into `aws-infraestructure/infrastructure/lambda/`
        run: |
          rm -rf aws-infraestructure/infrastructure/lambda/orders-service
          mkdir -p aws-infraestructure/infrastructure/lambda/orders-service
          rsync -av --progress ./ aws-infraestructure/infrastructure/lambda/orders-service/ --exclude aws-infraestructure

      - name: Overwrite `config.json` in `aws-infraestructure/infrastructure/`
        run: |
          cp -f aws-infraestructure/infrastructure/lambda/orders-service/config.json aws-infraestructure/infrastructure/config.json

      - name: Install Dependencies for Lambda
        run: |
          cd aws-infraestructure/infrastructure/lambda/orders-service
          npm install --production

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install CDK Dependencies
        run: |
          cd aws-infraestructure/infrastructure
          pip install -r requirements.txt

      - name: Deploy Lambda
        run: |
          cd aws-infraestructure
          cdk synth
          cdk deploy LambdaStack-dev
